from .camera_model import (
    Camera,
    CameraCreate,
    CameraUpdate,
    CameraWithTimelapse,
    CameraWithLastImage,
    CameraWithStats,
    CameraStats,
    CameraDetailsResponse,
    LogForCamera,
)
from .timelapse_model import (
    Timelapse,
    TimelapseCreate,
    TimelapseUpdate,
    TimelapseWithDetails,
)
from .video_model import Video, VideoCreate, VideoUpdate, VideoWithDetails
from .image_model import Image, ImageCreate, ImageWithDetails
from .settings_model import Setting, SettingCreate, SettingUpdate
from .log_model import Log, LogCreate
from .shared_models import (
    VideoGenerationMode,
    VideoAutomationMode,
    VideoGenerationSettings,
    VideoGenerationSettingsOptional,
    VideoAutomationSettings,
    VideoAutomationSettingsOptional,
    CorruptionDetectionSettings,
    CorruptionDetectionSettingsOptional,
    BaseStats,
    CameraHealthStatus,
    TimelapseStatistics,
    CameraStatistics,
    VideoGenerationJob,
    VideoGenerationJobWithDetails,
    VideoGenerationJobCreate,
    VideoStatistics,
    TimelapseForCleanup,
    TimelapseVideoSettings,
    CorruptionSettings,
)

__all__ = [
    # Core Models
    "Camera",
    "CameraCreate",
    "CameraUpdate",
    "CameraWithTimelapse",
    "CameraWithLastImage",
    "CameraWithStats",
    "CameraStats",
    "CameraDetailsResponse",
    "LogForCamera",
    "Timelapse",
    "TimelapseCreate",
    "TimelapseUpdate",
    "TimelapseWithDetails",
    "Video",
    "VideoCreate",
    "VideoUpdate",
    "VideoWithDetails",
    "Image",
    "ImageCreate",
    "ImageWithDetails",
    "Setting",
    "SettingCreate",
    "SettingUpdate",
    "Log",
    "LogCreate",
    # Shared Models
    "VideoGenerationMode",
    "VideoAutomationMode",
    "VideoGenerationSettings",
    "VideoGenerationSettingsOptional",
    "VideoAutomationSettings",
    "VideoAutomationSettingsOptional",
    "CorruptionDetectionSettings",
    "CorruptionDetectionSettingsOptional",
    "BaseStats",
    "CameraHealthStatus",
    "TimelapseStatistics",
    "CameraStatistics",
    "VideoGenerationJob",
    "VideoGenerationJobWithDetails",
    "VideoGenerationJobCreate",
    "VideoStatistics",
    "TimelapseForCleanup",
    "TimelapseVideoSettings",
    "CorruptionSettings",
]
