from . import (
    camera_crop_router,
    camera_routers,
    corruption_routers,
    dashboard_routers,
    health_routers,
    image_routers,
    image_serving_routers,
    log_routers,
    monitoring_routers,
    overlay_routers,
    settings_routers,
    sse_routers,
    thumbnail_routers,
    timelapse_routers,
    video_automation_routers,
    video_routers,
)

__all__ = [
    "camera_crop_router",
    "camera_routers",
    "corruption_routers",
    "dashboard_routers",
    "health_routers",
    "image_routers",
    "image_serving_routers",
    "log_routers",
    "monitoring_routers",
    "overlay_routers",
    "settings_routers",
    "sse_routers",
    "thumbnail_routers",
    "timelapse_routers",
    "video_automation_routers",
    "video_routers",
]
